### PR TITLE
TAPI OAM model updates as per TAPI/IMP calls from 08/14, 8/17 & 8/22

### PR DESCRIPTION
**Pull request by karthik-sethuraman**
- moved MEP/MIP containment to MEG, ME now aggregates MEP/MIP to allow for sharing of MEPs by multiple MEs in case of rooted-multipoint
- added an association from ME to Connection Route
- flattened MEP by removing source/sink/bi pacs and moving their attributes into MEP
- added layerProtocolName attribute to MEP/MIP
- added adminState attribute to pro-active/on-demand measurement jobs

Also includes Capacity datatype fixes
- Updated comment for totalSize attribute to indicate that in case of bandwidthProfile, this is expected to same as CIR
- renamed FixedCapacityValue datatype to CapacityValue
- made bandwidthProfile attribute as optional
- changed the type from Integer to CapacityValue for following BandwidthProfile attributes: committedInformationRate, committedBustSize, peakInformationRate & peakBurstSize
- removed the "NOT_APPLICABLE" enum value for CapacityUnit and BandwidthProfileTYpe enumerations

And fix for #247 - removed multiple keys for the TopologyPac datatypes

### CODE REVIEW

**Comment by RodLU** [comment]
Hi @karthik-sethuraman , hope not to removed the "NOT_APPLICABLE" enum value for CapacityUnit. Since the "NOT_APPLICABLE" enum can be used to make the Capacity totalSize express the number of ODUk TS. Although it seems there is another better way to express this, I think we can treat it as a temporary solution.

**Comment by bzeuner** [comment]
@RodLU : Where is the CapacityUnit defined?

**Comment by RodLU** [comment]
@bzeuner CapacityUnit is defined in the TapiCommon.uml after Karthik's pull request, which is used in Capacity -> totalSize -> CapacityValue -> unit.

**Comment by bzeuner** [comment]
@RodLU Thank you.
"NOT_APPLICABLE" is not in CapacityUnit:
greenshot

**Comment by RodLU** [comment]
@bzeuner Yes, but "NOT_APPLICABLE" was in CapacityUnit, hope not to remove the "NOT_APPLICABLE" enum value for CapacityUnit as mentioned.

**Pull request merged**
